In [1]:
import pandas as pd

In [6]:
df =  pd.read_excel("maindata/01_제공데이터/2020 빅콘테스트 데이터분석분야-챔피언리그_2019년 실적데이터_v1_200818.xlsx", skiprows=[0])
df2 = pd.read_excel("maindata/02_평가데이터/2020 빅콘테스트 데이터분석분야-챔피언리그_2020년 6월 판매실적예측데이터(평가데이터).xlsx", skiprows=[0])

In [7]:
df

,방송일시,노출(분),마더코드,상품코드,상품명,상품군,판매단가,취급액
0,2019-01-01 06:00:00,20.000000,100346,201072,테이트 남성 셀린니트3종,의류,39900,2099000.0
1,2019-01-01 06:00:00,NaN,100346,201079,테이트 여성 셀린니트3종,의류,39900,4371000.0
2,2019-01-01 06:20:00,20.000000,100346,201072,테이트 남성 셀린니트3종,의류,39900,3262000.0
3,2019-01-01 06:20:00,NaN,100346,201079,테이트 여성 셀린니트3종,의류,39900,6955000.0
4,2019-01-01 06:40:00,20.000000,100346,201072,테이트 남성 셀린니트3종,의류,39900,6672000.0
...,...,...,...,...,...,...,...,...
38304,2020-01-01 00:20:00,20.000000,100073,200196,삼성화재 행복한파트너 주택화재보험(1912),무형,0,NaN
38305,2020-01-01 00:40:00,20.000000,100073,200196,삼성화재 행복한파트너 주택화재보험(1912),무형,0,NaN
38306,2020-01-01 01:00:00,20.000000,100073,200196,삼성화재 행복한파트너 주택화재보험(1912),무형,0,NaN
38307,2020-01-01 01:20:00,20.000000,100490,201478,더케이 예다함 상조서비스(티포트),무형,0,NaN
38308,2020-01-01 01:40:00,17.166667,100490,201478,더케이 예다함 상조서비스(티포트),무형,0,NaN

In [8]:
df2

,방송일시,노출(분),마더코드,상품코드,상품명,상품군,판매단가,취급액
0,2020-06-01 06:20:00,20.000000,100650,201971,잭필드 남성 반팔셔츠 4종,의류,59800,NaN
1,2020-06-01 06:40:00,20.000000,100650,201971,잭필드 남성 반팔셔츠 4종,의류,59800,NaN
2,2020-06-01 07:00:00,20.000000,100650,201971,잭필드 남성 반팔셔츠 4종,의류,59800,NaN
3,2020-06-01 07:20:00,20.000000,100445,202278,쿠미투니카 쿨 레이시 란쥬쉐이퍼&팬티,속옷,69900,NaN
4,2020-06-01 07:40:00,20.000000,100445,202278,쿠미투니카 쿨 레이시 란쥬쉐이퍼&팬티,속옷,69900,NaN
...,...,...,...,...,...,...,...,...
2886,2020-07-01 00:20:00,20.000000,100660,201989,쉴렉스 안마의자 렌탈서비스,무형,0,NaN
2887,2020-07-01 00:40:00,20.000000,100660,201989,쉴렉스 안마의자 렌탈서비스,무형,0,NaN
2888,2020-07-01 01:00:00,20.000000,100660,201989,쉴렉스 안마의자 렌탈서비스,무형,0,NaN
2889,2020-07-01 01:20:00,20.000000,100261,200875,아놀드파마 티셔츠레깅스세트,의류,69900,NaN
2890,2020-07-01 01:40:00,15.933333,100261,200875,아놀드파마 티셔츠레깅스세트,의류,69900,NaN

In [16]:
# 제공데이터 마더코드mcode 상품코드item

mcode = df["마더코드"].drop_duplicates().tolist()
item = df["상품코드"].drop_duplicates().tolist()

print(len(mcode))
print(len(item))

716
2124

In [19]:
# 평가데이터 마더코드 mcode_t, 상품코드 item_t

mcode_t = df2['마더코드'].drop_duplicates().tolist()
item_t = df2["상품코드"].drop_duplicates().tolist()

print(len(mcode_t))
print(len(item_t))

225
417

In [22]:
# 마더코드 비교 (평가데이터에만 있는 코드)

mlist = []
for i in mcode_t:
    if i not in mcode:
        mlist.append(i)
        
print(len(mlist))
print(mlist)

134
[100650, 100381, 100012, 100570, 100537, 100383, 100555, 100526, 100728, 100785, 100068, 100388, 100690, 100461, 100804, 100137, 100486, 100630, 100514, 100559, 100648, 100647, 100331, 100186, 100546, 100425, 100105, 100593, 100621, 100116, 100384, 100800, 100333, 100259, 100077, 100428, 100767, 100108, 100301, 100525, 100590, 100639, 100407, 100730, 100691, 100726, 100424, 100633, 100592, 100004, 100457, 100686, 100160, 100141, 100060, 100159, 100772, 100778, 100806, 100521, 100361, 100645, 100560, 100825, 100110, 100005, 100847, 100426, 100393, 100008, 100071, 100082, 100396, 100123, 100138, 100291, 100524, 100133, 100799, 100591, 100733, 100035, 100661, 100544, 100649, 100358, 100402, 100759, 100119, 100092, 100659, 100303, 100431, 100796, 100120, 100350, 100706, 100349, 100030, 100746, 100660, 100513, 100429, 100365, 100313, 100550, 100487, 100007, 100663, 100662, 100760, 100485, 100059, 100674, 100842, 100552, 100739, 100538, 100363, 100480, 100003, 100542, 100535, 100823, 100727, 100419, 100437, 100106, 100207, 100183, 100561, 100011, 100014, 100261]

In [23]:
# 상품코드 비교 (평가데이터에만 있는 코드)

itemlist = []
for i in item_t:
    if i not in item:
        itemlist.append(i)
        
print(len(itemlist ))
print(itemlist)

390
[201971, 202278, 201247, 201091, 200016, 200217, 201673, 201671, 201641, 201150, 201616, 201251, 201250, 200424, 201319, 201520, 200416, 200419, 200422, 200724, 200727, 200730, 201016, 201017, 201643, 201596, 200668, 200867, 201130, 202125, 202296, 201454, 202460, 202459, 200651, 200588, 201024, 200184, 200186, 200179, 200181, 201277, 201279, 201276, 201258, 201259, 201699, 201752, 201698, 201751, 201697, 201750, 201041, 200273, 200272, 200274, 202052, 201418, 201037, 200917, 200266, 200270, 200900, 202368, 200368, 200369, 201464, 202259, 201938, 201578, 201656, 201033, 200020, 201011, 200143, 201969, 201968, 201039, 200621, 202252, 201632, 201337, 201336, 201334, 201335, 200291, 200289, 200292, 200290, 201813, 201817, 201811, 201815, 201923, 200317, 200316, 201253, 201252, 202364, 201882, 201042, 200873, 200212, 201341, 202247, 202246, 200300, 200966, 201595, 202226, 202224, 201808, 201957, 201316, 201294, 202128, 202129, 200092, 200079, 200083, 200099, 200067, 200064, 200060, 200059, 200723, 200726, 200729, 201814, 201818, 201812, 201816, 200421, 200418, 200415, 200486, 200553, 200188, 200187, 200063, 200058, 200096, 200066, 202053, 200426, 202241, 202244, 200705, 200689, 200709, 200693, 200713, 200697, 202123, 202120, 202121, 200072, 200074, 200195, 200863, 201331, 201333, 201332, 201943, 200994, 200995, 201447, 201676, 201728, 201810, 200005, 201410, 202042, 202040, 200565, 200380, 200378, 200379, 200381, 201954, 200147, 200564, 202258, 202275, 202371, 201588, 201148, 200425, 201966, 201965, 202391, 202396, 201657, 202428, 202427, 200304, 200006, 200007, 202506, 202507, 201338, 201269, 201271, 200124, 201953, 201732, 201680, 201731, 201679, 201730, 201678, 201729, 201677, 200484, 200551, 200012, 200193, 200221, 200222, 201283, 201273, 201274, 201275, 200331, 200295, 200293, 200296, 200294, 200370, 201574, 202240, 202243, 200198, 200940, 200941, 201593, 201592, 201594, 202387, 200358, 200357, 202257, 200420, 200417, 200414, 202363, 201145, 200722, 200725, 200728, 200183, 200185, 200178, 200180, 201809, 201591, 200704, 200688, 200708, 200692, 200712, 200696, 202149, 200057, 201990, 201629, 200280, 201636, 201970, 201139, 201311, 201286, 202212, 200323, 200321, 200322, 200324, 200251, 201242, 201952, 201988, 200968, 201344, 202359, 200326, 200328, 200325, 200327, 201121, 202071, 201385, 201386, 200021, 201120, 201119, 200044, 200045, 202186, 201950, 201989, 201577, 201342, 201153, 201154, 200999, 201637, 201465, 200997, 200182, 200177, 202225, 202223, 201726, 201727, 201725, 201724, 200010, 200011, 200654, 201996, 201995, 201994, 201993, 201992, 201991, 202148, 202213, 202041, 202039, 201782, 201783, 201784, 200216, 201463, 201626, 200146, 200214, 202511, 202018, 202017, 202486, 202485, 201639, 202166, 202084, 201617, 201151, 200582, 201456, 200004, 200003, 201623, 201014, 202242, 202245, 201613, 201614, 201951, 201949, 201948, 202425, 202424, 202423, 201147, 200192, 202124, 202122, 201324, 201672, 201354, 200297, 200299, 200743, 201618, 200617, 200616, 201658, 200015, 201627, 201458, 202323, 202321, 202322, 202318, 202319, 202320, 200862, 200019, 200022, 200875]